[package]
name = "audio_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
arc-swap = "1.7.1"
interavl = "0.3.0"
once_cell = "1.21.3"
slotmap = "1.0.7"
symphonia = "0.5.4"
thiserror = "2.0.16"
dasp = "0.11.0"
time = { path = "crates/time" }
audio_buffer = { path = "crates/audio_buffer" }
audio_graph = { path = "crates/audio_graph" }

[workspace]
members = ["crates/time", "crates/audio_buffer", "crates/audio_graph"]
