[package]
name = "audio_buffer"
version = "0.1.0"
edition = "2024"

[dependencies]
dasp = { version = "0.11.0" }
lending-iterator = "0.1.7"
symphonia = "0.5.4"
thiserror = "2.0.17"
time = { path = "../time" }
